### ISSUE TITLE
Problem installing on Linux

### ISSUE THREAD

**Issue by danielplatt** [xingdi-eric-yuan/TextWorld-Coin-Collector#10]
Running the command `pip install https://github.com/microsoft/TextWorld/archive/refs/heads/coin_collector.zip` on Linux gives me the following output. After this, the module package cannot be used. Tried with Python 3.6, 3.7, 3.8. Same when cloning the CoinCollector branch of Textworld and running `pip install .`. Installing the Textworld Master branch works without problems. How can I install CoinCollector?

```
(venvFresh) (base) daniel@daniel-ubuntu:~/PycharmProjects/TextWorldCopy$ pip install https://github.com/microsoft/TextWorld/archive/refs/heads/coin_collector.zip
Collecting https://github.com/microsoft/TextWorld/archive/refs/heads/coin_collector.zip
  Using cached https://github.com/microsoft/TextWorld/archive/refs/heads/coin_collector.zip
Collecting numpy>=1.13.1
  Using cached numpy-1.21.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting tqdm>=4.17.1
  Using cached tqdm-4.61.2-py2.py3-none-any.whl (76 kB)
Collecting cffi>=1.0.0
  Using cached cffi-1.14.6-cp38-cp38-manylinux1_x86_64.whl (411 kB)
Collecting networkx>=2
  Using cached networkx-2.5.1-py3-none-any.whl (1.6 MB)
Collecting pyyaml>=3.12
  Using cached PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
Collecting urwid>=2.0.1
  Using cached urwid-2.1.2-cp38-cp38-linux_x86_64.whl
Collecting more_itertools
  Using cached more_itertools-8.8.0-py3-none-any.whl (48 kB)
Collecting tatsu>=4.2.5
  Using cached TatSu-5.6.1-py2.py3-none-any.whl (94 kB)
Collecting hashids>=1.2.0
  Using cached hashids-1.3.1-py2.py3-none-any.whl (6.6 kB)
Collecting jericho>=1.1.1
  Using cached jericho-3.0.5-py3-none-any.whl
Collecting pybars3>=0.9.3
  Using cached pybars3-0.9.7-py3-none-any.whl
Collecting flask>=1.0.2
  Using cached Flask-2.0.1-py3-none-any.whl (94 kB)
Collecting selenium>=3.12.0
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting greenlet==0.4.13
  Using cached greenlet-0.4.13-cp38-cp38-linux_x86_64.whl
Collecting gevent==1.3.5
  Using cached gevent-1.3.5-cp38-cp38-linux_x86_64.whl
Collecting pillow>=5.1.0
  Using cached Pillow-8.3.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.0 MB)
Collecting prompt-toolkit<2.0.0,>=1.0.15
  Using cached prompt_toolkit-1.0.18-py3-none-any.whl (245 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting click>=7.1.2
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting Jinja2>=3.0
  Using cached Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting Werkzeug>=2.0
  Using cached Werkzeug-2.0.1-py3-none-any.whl (288 kB)
Collecting itsdangerous>=2.0
  Using cached itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting spacy>=2.1.0
  Using cached spacy-3.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.5 MB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.0.1-cp38-cp38-manylinux2010_x86_64.whl (30 kB)
Collecting decorator<5,>=4.3
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting six>=1.9.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting PyMeta3>=0.5.1
  Using cached PyMeta3-0.5.1-py3-none-any.whl
Collecting urllib3
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting wasabi<1.1.0,>=0.8.1
  Using cached wasabi-0.8.2-py3-none-any.whl (23 kB)
Collecting thinc<8.1.0,>=8.0.7
  Using cached thinc-8.0.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (628 kB)
Collecting cymem<2.1.0,>=2.0.2
  Using cached cymem-2.0.5-cp38-cp38-manylinux2014_x86_64.whl (35 kB)
Collecting srsly<3.0.0,>=2.4.1
  Using cached srsly-2.4.1-cp38-cp38-manylinux2014_x86_64.whl (458 kB)
Collecting packaging>=20.0
  Using cached packaging-21.0-py3-none-any.whl (40 kB)
Collecting pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4
  Using cached pydantic-1.8.2-cp38-cp38-manylinux2014_x86_64.whl (13.7 MB)
Collecting murmurhash<1.1.0,>=0.28.0
  Using cached murmurhash-1.0.5-cp38-cp38-manylinux2014_x86_64.whl (20 kB)
Collecting blis<0.8.0,>=0.4.0
  Using cached blis-0.7.4-cp38-cp38-manylinux2014_x86_64.whl (9.8 MB)
Collecting typer<0.4.0,>=0.3.0
  Using cached typer-0.3.2-py3-none-any.whl (21 kB)
Collecting spacy-legacy<3.1.0,>=3.0.7
  Using cached spacy_legacy-3.0.8-py2.py3-none-any.whl (14 kB)
Collecting pathy>=0.3.5
  Using cached pathy-0.6.0-py3-none-any.whl (42 kB)
Collecting preshed<3.1.0,>=3.0.2
  Using cached preshed-3.0.5-cp38-cp38-manylinux2014_x86_64.whl (130 kB)
Collecting catalogue<2.1.0,>=2.0.4
  Using cached catalogue-2.0.4-py3-none-any.whl (16 kB)
Requirement already satisfied: setuptools in ./venvFresh/lib/python3.8/site-packages (from spacy>=2.1.0->jericho>=1.1.1->textworld==0.0.3) (57.1.0)
Collecting requests<3.0.0,>=2.13.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting smart-open<6.0.0,>=5.0.0
  Using cached smart_open-5.1.0-py3-none-any.whl (57 kB)
Collecting typing-extensions>=3.7.4.3
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting click>=7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Using legacy 'setup.py install' for textworld, since package 'wheel' is not installed.
Installing collected packages: typing-extensions, numpy, murmurhash, cymem, click, catalogue, wasabi, urllib3, typer, srsly, smart-open, pyparsing, pydantic, preshed, MarkupSafe, idna, chardet, certifi, blis, tqdm, thinc, spacy-legacy, requests, pathy, packaging, Jinja2, Werkzeug, wcwidth, spacy, six, PyMeta3, pycparser, itsdangerous, greenlet, decorator, urwid, tatsu, selenium, pyyaml, pybars3, prompt-toolkit, pillow, networkx, more-itertools, jericho, hashids, gevent, flask, cffi, textworld
    Running setup.py install for textworld ... error
    ERROR: Command errored out with exit status 1:
     command: /home/daniel/PycharmProjects/TextWorldCopy/venvFresh/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-px9vst7e/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-px9vst7e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8n8ri_fx/install-record.txt --single-version-externally-managed --compile --install-headers /home/daniel/PycharmProjects/TextWorldCopy/venvFresh/include/site/python3.8/textworld
         cwd: /tmp/pip-req-build-px9vst7e/
    Complete output (134 lines):
    running install
    Running post install task
    + echo 'Running setup.sh...'
    Running setup.sh...
    ++ uname -s
    + unameOut=Linux
    + case "${unameOut}" in
    + machine=Linux
    + tatsu textworld/logic/logic.ebnf -o textworld/logic/parser.py -G textworld/logic/model.py
    ------------------------------------------------------------------------
             284  lines in grammar
              44  rules in grammar
             300  nodes in AST
    + cd textworld/thirdparty/
    + '[' '!' -e I7_6M62_Linux_all.tar.gz ']'
    + echo 'Downloading Inform7 CLI'
    Downloading Inform7 CLI
    + curl -LO http://inform7.com/apps/6M62/I7_6M62_Linux_all.tar.gz
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
     10 22.1M   10 2322k    0     0  2389k      0  0:00:09 --:--:--  0:00:09 2386k
     39 22.1M   39 8865k    0     0  4490k      0  0:00:05  0:00:01  0:00:04 4488k
     58 22.1M   58 12.9M    0     0  4460k      0  0:00:05  0:00:02  0:00:03 4458k
     77 22.1M   77 17.1M    0     0  4414k      0  0:00:05  0:00:03  0:00:02 4413k
     92 22.1M   92 20.4M    0     0  4191k      0  0:00:05  0:00:04  0:00:01 4190k
    100 22.1M  100 22.1M    0     0  4097k      0  0:00:05  0:00:05 --:--:-- 4459k
    + '[' Linux == Mac ']'
    + '[' '!' -d inform7-6M62 ']'
    + tar xf I7_6M62_Linux_all.tar.gz
    + echo 'Installing Inform7 CLI'
    Installing Inform7 CLI
    + cd inform7-6M62/
    + ./install-inform7.sh --prefix /tmp/pip-req-build-px9vst7e/textworld/thirdparty/inform7-6M62
    + '[' Linux == Mac ']'
    + '[' '!' -d frotz ']'
    + echo 'Installing frotz'
    Installing frotz
    + git clone https://github.com/danielricks/frotz.git
    Cloning into 'frotz'...
    + cd frotz/
    + make -B dumb
    gcc -O2  -o src/common/buffer.o -c src/common/buffer.c
    gcc -O2  -o src/common/err.o -c src/common/err.c
    gcc -O2  -o src/common/fastmem.o -c src/common/fastmem.c
    gcc -O2  -o src/common/files.o -c src/common/files.c
    gcc -O2  -o src/common/hotkey.o -c src/common/hotkey.c
    gcc -O2  -o src/common/input.o -c src/common/input.c
    gcc -O2  -o src/common/main.o -c src/common/main.c
    gcc -O2  -o src/common/math.o -c src/common/math.c
    gcc -O2  -o src/common/object.o -c src/common/object.c
    gcc -O2  -o src/common/process.o -c src/common/process.c
    gcc -O2  -o src/common/quetzal.o -c src/common/quetzal.c
    gcc -O2  -o src/common/random.o -c src/common/random.c
    gcc -O2  -o src/common/redirect.o -c src/common/redirect.c
    gcc -O2  -o src/common/screen.o -c src/common/screen.c
    gcc -O2  -o src/common/sound.o -c src/common/sound.c
    gcc -O2  -o src/common/stream.o -c src/common/stream.c
    gcc -O2  -o src/common/table.o -c src/common/table.c
    gcc -O2  -o src/common/text.o -c src/common/text.c
    gcc -O2  -o src/common/variable.o -c src/common/variable.c
    
    Archiving common code...
    /usr/bin/ar rc src/frotz_common.a src/common/buffer.o src/common/err.o src/common/fastmem.o src/common/files.o src/common/hotkey.o src/common/input.o src/common/main.o src/common/math.o src/common/object.o src/common/process.o src/common/quetzal.o src/common/random.o src/common/redirect.o src/common/screen.o src/common/sound.o src/common/stream.o src/common/table.o src/common/text.o src/common/variable.o
    /usr/bin/ranlib src/frotz_common.a
    
    gcc -O2 -o src/dumb/dumb_init.o -c src/dumb/dumb_init.c
    gcc -O2 -o src/dumb/dumb_input.o -c src/dumb/dumb_input.c
    src/dumb/dumb_input.c: In function ‘xgetchar’:
    src/dumb/dumb_input.c:70:22: warning: zero-length gnu_printf format string [-Wformat-zero-length]
       70 |      fprintf(stderr, "");
          |                      ^~
    src/dumb/dumb_input.c: In function ‘dumb_read_line’:
    src/dumb/dumb_input.c:267:14: warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 2 has type ‘long int’ [-Wformat=]
      267 |    printf("%.*s", next_page - current_page, current_page);
          |            ~~^~   ~~~~~~~~~~~~~~~~~~~~~~~~
          |              |              |
          |              int            long int
    gcc -O2 -o src/dumb/dumb_output.o -c src/dumb/dumb_output.c
    gcc -O2 -o src/dumb/dumb_pic.o -c src/dumb/dumb_pic.c
    
    Archiving dumb interface code...
    /usr/bin/ar rc src/frotz_dumb.a src/dumb/dumb_init.o src/dumb/dumb_input.o src/dumb/dumb_output.o src/dumb/dumb_pic.o
    /usr/bin/ranlib src/frotz_dumb.a
    
    gcc -o dfrotz src/frotz_common.a src/frotz_dumb.a
    + echo 'Installing cheapglk'
    Installing cheapglk
    + cd glulx/cheapglk
    + make -B
    cc -g -Wall -Werror -std=gnu99    -c -o cgfref.o cgfref.c
    cc -g -Wall -Werror -std=gnu99    -c -o cggestal.o cggestal.c
    cc -g -Wall -Werror -std=gnu99    -c -o cgmisc.o cgmisc.c
    cc -g -Wall -Werror -std=gnu99    -c -o cgstream.o cgstream.c
    cc -g -Wall -Werror -std=gnu99    -c -o cgstyle.o cgstyle.c
    cc -g -Wall -Werror -std=gnu99    -c -o cgwindow.o cgwindow.c
    cc -g -Wall -Werror -std=gnu99    -c -o cgschan.o cgschan.c
    cc -g -Wall -Werror -std=gnu99    -c -o cgdate.o cgdate.c
    cc -g -Wall -Werror -std=gnu99    -c -o cgunicod.o cgunicod.c
    cc -g -Wall -Werror -std=gnu99    -c -o main.o main.c
    cc -g -Wall -Werror -std=gnu99    -c -o gi_dispa.o gi_dispa.c
    cc -g -Wall -Werror -std=gnu99    -c -o gi_blorb.o gi_blorb.c
    cc -g -Wall -Werror -std=gnu99    -c -o gi_debug.o gi_debug.c
    cc -g -Wall -Werror -std=gnu99    -c -o cgblorb.o cgblorb.c
    cc -g -Wall -Werror -std=gnu99    -c -o agent.o agent.c
    agent.c:11:10: fatal error: uuid/uuid.h: No such file or directory
       11 | #include <uuid/uuid.h>
          |          ^~~~~~~~~~~~~
    compilation terminated.
    make: *** [<builtin>: agent.o] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-px9vst7e/setup.py", line 41, in <module>
        setup(
      File "/home/daniel/PycharmProjects/TextWorldCopy/venvFresh/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-px9vst7e/setup.py", line 23, in run
        self.execute(_pre_install, (self.install_lib,),
      File "/usr/lib/python3.8/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python3.8/distutils/util.py", line 303, in execute
        func(*args)
      File "/tmp/pip-req-build-px9vst7e/setup.py", line 18, in _pre_install
        check_call(['./setup.sh'], shell=True, cwd=os.getcwd())
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['./setup.sh']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/daniel/PycharmProjects/TextWorldCopy/venvFresh/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-px9vst7e/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-px9vst7e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8n8ri_fx/install-record.txt --single-version-externally-managed --compile --install-headers /home/daniel/PycharmProjects/TextWorldCopy/venvFresh/include/site/python3.8/textworld Check the logs for full command output.
```

**Comment by danielplatt** [comment]
`sudo apt-get install uuid-dev` solved it for me.
