### ISSUE TITLE
Problem training agent

### ISSUE THREAD

**Issue by ronentk** [xingdi-eric-yuan/TextWorld-Coin-Collector#3]
Hi,
I'm trying to run the training procedure detailed in the README. 
When running `python lstm_dqn_baseline/train_single_generate_agent.py -c lstm_dqn_baseline/config/` 
I get a `Game failed to start properly` error. However, I can successfully manually run the specified game using `tw-play`.

The full message is as follows:
```
python lstm_dqn_baseline/train_single_generate_agent.py -c lstm_dqn_baseline/config/
INFO:__main__:current git commit: b'ae4b28a29d47967434d8a070f0e90fe4b2e67069\n'
Setting up TextWorld environment...
Done.
/home/ronent/env/TextWorld-Coin-Collector/lstm_dqn_baseline/../helpers/layers.py:113: UserWarning: nn.init.orthogonal is now deprecated in favor of nn.init.orthogonal_.
  torch.nn.init.orthogonal(self.weight_hh.data)
/home/ronent/env/TextWorld-Coin-Collector/lstm_dqn_baseline/../helpers/layers.py:114: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  torch.nn.init.xavier_uniform(self.weight_ih.data, gain=1)
/home/ronent/env/TextWorld-Coin-Collector/lstm_dqn_baseline/../helpers/model.py:70: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  torch.nn.init.xavier_uniform(self.action_scorer_shared.weight.data, gain=1)
/home/ronent/env/TextWorld-Coin-Collector/lstm_dqn_baseline/../helpers/model.py:71: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  torch.nn.init.xavier_uniform(self.action_scorer_action.weight.data, gain=1)
/home/ronent/env/TextWorld-Coin-Collector/lstm_dqn_baseline/../helpers/model.py:72: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  torch.nn.init.xavier_uniform(self.action_scorer_object.weight.data, gain=1)
*** fatal error: failed to read entire game file ***
glk_comm.c: Could not read msg size: Success
Process Process-10:
Traceback (most recent call last):
  File "/home/ronent/env/anaconda3/envs/textworld-clean/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ronent/env/anaconda3/envs/textworld-clean/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ronent/env/anaconda3/envs/textworld-clean/lib/python3.7/site-packages/gym_textworld/envs/util_envs.py", line 26, in _child
    result = fct(*command[2])
  File "/home/ronent/env/anaconda3/envs/textworld-clean/lib/python3.7/site-packages/gym/wrappers/time_limit.py", line 44, in reset
    return self.env.reset()
  File "/home/ronent/env/anaconda3/envs/textworld-clean/lib/python3.7/site-packages/gym_textworld/envs/coin_collector.py", line 176, in reset
    self.game_state = self.textworld_env.reset()
  File "/home/ronent/env/anaconda3/envs/textworld-clean/lib/python3.7/site-packages/textworld/envs/glulx/git_glulx_ml.py", line 498, in reset
    raise ValueError("Game failed to start properly: {}.".format(self._gamefile))
ValueError: Game failed to start properly: gen_games/twcc_easy_level10_gamesize100_step50_seed9_train-v0/twcc_easy_level10_gamesize100_step50_seed9_train-v0_oEeGmKuZc0gdt7Oeu6LWf9OVs8Gb.ulx.
Traceback (most recent call last):
  File "lstm_dqn_baseline/train_single_generate_agent.py", line 287, in <module>
    train(config=config)
  File "lstm_dqn_baseline/train_single_generate_agent.py", line 126, in train
    obs, infos = env.reset()
  File "/home/ronent/env/anaconda3/envs/textworld-clean/lib/python3.7/site-packages/gym_textworld/envs/util_envs.py", line 120, in reset
    result = env.result()
  File "/home/ronent/env/anaconda3/envs/textworld-clean/lib/python3.7/site-packages/gym_textworld/envs/util_envs.py", line 56, in result
    return self._pipe.recv()
  File "/home/ronent/env/anaconda3/envs/textworld-clean/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/ronent/env/anaconda3/envs/textworld-clean/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/ronent/env/anaconda3/envs/textworld-clean/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError

```

Any ideas what could be wrong?
Thanks

**Comment by MarcCote** [comment]
Hi, thanks for reporting this error. I think what might have happened here is multiple games are getting generated at the same time and written to the same file i.e. file corruption. 

Can you try calling `tw-make.py` for each env_id found in the config file? That is:
```
./gym_textworld/scripts/tw-make.py twcc_easy_level10_gamesize100_step50_seed9_train
./gym_textworld/scripts/tw-make.py twcc_easy_level10_gamesize10_step50_seed9_validation
./gym_textworld/scripts/tw-make.py twcc_easy_level5_gamesize10_step50_seed1_test
./gym_textworld/scripts/tw-make.py twcc_easy_level10_gamesize10_step50_seed0_test
./gym_textworld/scripts/tw-make.py twcc_easy_level15_gamesize10_step50_seed3_test
./gym_textworld/scripts/tw-make.py twcc_easy_level20_gamesize10_step50_seed2_test
./gym_textworld/scripts/tw-make.py twcc_easy_level30_gamesize10_step50_seed3_test
```
Then, retry the training script.

Let us know if that works for you. We'll adjust the README and the training scripts to make it more user-friendly.

**Comment by ronentk** [comment]
Hi, it does resolve the issue- thanks :)

Also could be worth mentioning that pytorch should be version 0.3, with 0.4 it seems there are some API changes that break the training procedure.

**Comment by xingdi-eric-yuan** [comment]
Hi @ronentk , good point, we are working on to make this reproducible on pytorch 0.4 and later version, but as you said, it would be good to mention the current version only works on 0.3. Thanks!

**Comment by MarcCote** [comment]
@anantzoid how is your PR to port the code to Pytorch 0.4 coming along?

**Comment by anantzoid** [comment]
@MarcCote I should be able to push the changes by Wednesday.

**Comment by xingdi-eric-yuan** [comment]
@anantzoid  I'm almost done making it work in pt0.4, I'll have a PR soon, maybe you can take a look of it?

**Comment by anantzoid** [comment]
@xingdi-eric-yuan Sure, that works.

**Comment by xingdi-eric-yuan** [comment]
@anantzoid it's in [PR#4](https://github.com/xingdi-eric-yuan/TextWorld-Coin-Collector/pull/4) . 
Hi @ronentk , we have updated the code to make it reproducible in pytorch 0.4, after merging PR#4 it won't work on pytorch 0.3 anymore, I'll let you know and please pull the latest code then.

**Comment by xingdi-eric-yuan** [comment]
@ronentk Please pull master branch, it works on pytorch 0.4 now.

**Comment by ronentk** [comment]
Works, thanks :)
